kind: Service
apiVersion: v1
metadata:
  name: nickjgrahamcomdev
  namespace: nickjgrahamcomdev
spec:
  selector:
    app: nickjgrahamcomdev
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nickjgrahamcomdev
  namespace: nickjgrahamcomdev
  labels:
    app: nickjgrahamcomdev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nickjgrahamcomdev

  template:
    metadata:
      labels:
        app: nickjgrahamcomdev
  
    spec:
      containers:
      - name: nickjgrahamcomdev
        image: nicholasjgraham/nickjgraham.com:latest
        imagePullPolicy: Always
        env:
          - name: LOG_LEVEL
            value: "DEBUG"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
        readinessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            httpGet:
              scheme: HTTP
              port: 8080
              path: /health
        startupProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 1
            timeoutSeconds: 1
            periodSeconds: 10
            httpGet:
              scheme: HTTP
              port: 8080
              path: /ping
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: nickjgrahamcomdev
  name: nickjgrahamcomdev
  namespace: nickjgrahamcomdev
spec:
  rules:
  - host: nickjgraham-dev.nickwork.net
    http:
      paths:
      - backend:
          service:
            name: nickjgrahamcomdev
            port:
              number: 8080
        path: /
        pathType: Prefix
